### ISSUE TITLE
Infinite loop Retrieving audiobook url...

### ISSUE THREAD

**Issue by jdalbey** [jdalbey/libbyfetch#17]
At the point in the session where the message is displayed "`Retrieving audiobook url...`" it keeps displaying "`waiting`" repeatedly until the process is killed. 
To troubleshoot I tried to use the Libby website in a browser and the audiobook appeared in my Loans and when I clicked "Open Audiobook" a new page appeared with the message "Access to this magazine is not allowed with your active library card."  This happens for all the materials I have on loan (books and audiobooks).  (Maybe my card has been blocked for some reason?)  
So this scenario is probably pretty rare but `libbyfetch` should probably timeout after waiting for some period of time and try to dump whatever it knows to an error message.

**Comment by jdalbey** [comment]
Probably this is the page element to display when the timeout period expires:
`<p class="interview-episode-say"><span role="text">Access to this magazine is not allowed with your active library card.</span></p>`

**Comment by jdalbey** [comment]
Fixed in 57c364b418224680316bf4113c581bddd43f26c5
Added a limit to number of retries getting the url, then printing an error with the text from the span mentioned above.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the obtain_book_url function to include a timeout mechanism and improved error handling. If the audiobook URL is not retrieved within a specified time limit, the function will now terminate with an informative error message. This addresses the issue where the script would keep displaying 'waiting' indefinitely.

You can review changes in this commit: https://github.com/lattaai13/jdalbey-libbyfetch-17/commit/819d6e8be89574590cefbe2a06a2fccfe62f3b3b.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by flyswimr** [comment]
I am getting the same issue.

In LibbyApp from a phone and the libbyapp.com website:
-cannot open audiobook (but can still check audiobooks out), "Access to the magazine is not allowed with your active library card".
-cannot download, "Downloading failed for some reason.."

Script:   repeating waiting..waiting..waiting message after the message "Retrieving Audiobook URL"

From OverDrive (browser) am able to still listen to the audiobook.

This is from both library cards used for testing. Seems to be the case for regular/epub books as well. Accessing audiobooks from both Libby app and Libby browser seems to not work. Overdrive is intact.

**Comment by jdalbey** [comment]
@flyswimr  Very curious.  I phoned my library to ask about this issue and they didn't know what the problem was.  They could reproduce the error message on their computer but didn't know what was causing it. They suggested I come to the library and have them issue me a new library card.

**Comment by flyswimr** [comment]
If you want to talk offline via email on this let me know.  Replacing a library card, now allows usage of both Libby and Overdrive (browser only of course).  When before, could only use Overdrive in the browser.  I have not tried LF yet, can't chance if they block.

**Comment by jdalbey** [comment]
@flyswimr I corresponded with Libby support and can share their reply with you offline. Please email `jdalbey@calpoly.edu`
