### ISSUE TITLE
Hangs if Chrome not installed

### ISSUE THREAD

**Issue by jdalbey** [jdalbey/libbyfetch#18]
If the Chrome browser is not installed on the system Libby Fetch will hang after printing "Initializing LibbyApp."

**Comment by flyswimr** [comment]
I can confirm this.

**Comment by jdalbey** [comment]
Fixed in d0b2a624f8eb8321b785c5f4241b62a0d345bcec.  Added a timeout-decorator to the webdriver initialization.  (This adds a dependency on the timeout-decorator module).

**Comment by jdalbey** [comment]
Closing, fixed in d0b2a624f8eb8321b785c5f4241b62a0d345bcec.
