### ISSUE TITLE
Access to the magazine is not allowed with your active library card

### ISSUE THREAD

**Issue by flyswimr** [jdalbey/libbyfetch#19]
In LibbyApp from a phone and the libbyapp.com website: 
 -cannot open audiobook (but can still check audiobooks out), "Access to the magazine is not allowed with your active library card".
 -cannot download, "Downloading failed for some reason.."

Script:
- repeating waiting..waiting..waiting message after the message "Retrieving Audiobook URL"

From OverDrive (browser) **am able** to still listen to the audiobook.

This is from both library cards used for testing.  Seems to be the case for regular/epub books as well.  Accessing audiobooks from both Libby app and Libby browser seems to not work.  Overdrive is intact.

**Comment by flyswimr** [comment]
Adding to more relevant issue..

**Comment by jdalbey** [comment]
Duplicate of #17
