### ISSUE TITLE
Unable to Install Dependencies, pycurl (Windows)

### ISSUE THREAD

**Issue by OGQueenie** [jdalbey/libbyfetch#20]
You'll have to forgive me if this is a straightforward answer/fix and I'm just dumb, I'm fairly new to Python and coding in general, but from what I'm able to gather I seem to be having some trouble Installing one of the Dependencies namely pycurl, Is there anything I'm doing wrong? Is this a problem with how I've set things up? Where it gets tripped up is in the process of building the wheel, I've tried googling some of the errors I've been getting but nothing I do helps. I'm running Windows 11, and I've pasted the script below for you, I'd appreciate any advice/help you have! 

PS C:\Users\Owner\Downloads\libbyfetch-1.0.3> python3 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: blinker==1.7.0 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from -r requirements.txt (line 1)) (1.7.0)
Collecting packaging==24.2 (from -r requirements.txt (line 2))
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pycurl==7.45.3 (from -r requirements.txt (line 3))
  Using cached pycurl-7.45.3.tar.gz (236 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 10
  ╰─> [1 lines of output]
      Please specify --curl-dir=/path/to/built/libcurl
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 10
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\Owner\Downloads\libbyfetch-1.0.3>

**Comment by jdalbey** [comment]
@OGQueenie I had this exact same error when I tried to install on Windows.  I described my efforts in #12.  Have a look at that and see if the solution I found works for you.  Let me know of your progress.

**Comment by tcjjr** [comment]
If I recall right, I think I got a similar 'wheel did not run' error when I first tried this yesterday, and I believe I solved it by installing setuptools for my Windows Python installation because that was missing from it:

Try this:
pip install setuptools

See if that helps, but YMMV (I claim no expertise with Python).

**Comment by jdalbey** [comment]
Thanks @tcjjr  for that tip.  I installed Python on Windows 11 by following [these instructions](https://gist.github.com/jdalbey/3de4fed637338ed8c5049a3253881a4d).  Then after unzipping the Libby Fetch release I installed the dependencies by using the `requirements.txt` file, like this: 
```
python -m pip install -r requirements.txt
```
Somehow this avoided the hiccup with `pyCurl`.
