### ISSUE TITLE
module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by OGQueenie** [jdalbey/libbyfetch#24]
Hey guys, Me again, I was finally able to get pycurl working by uninstalling and reinstalling it so thanks for that! I was able to log in and connect to Overdrive/Libby however I was experiencing issues similar to those described in #23 
I downloaded the new 1.04 release and now I'm experiencing a new error and seem unable to run the program.
I have copied/pasted what happens down below, If you guys have any advice please let me know, I'm watching some tutorials for Python on YouTube but I still don't understand much of it lol.

PS C:\Users\Owner\Downloads\libbyfetch-1.0.4> python3 libbyfetch.py
Initializing webdriver.
An error occurred for an unknown cause.
Exception type:  <class 'AttributeError'>
Message: module 'signal' has no attribute 'SIGALRM'
Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\libbyfetch-1.0.4\libbyfetch.py", line 489, in startup
    return initialize_driver()
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\timeout_decorator\timeout_decorator.py", line 75, in new_function
    old = signal.signal(signal.SIGALRM, handler)
                        ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGALRM'. Did you mean: 'SIGABRT'?
PS C:\Users\Owner\Downloads\libbyfetch-1.0.4>

**Comment by jdalbey** [comment]
@OGQueenie Glad you got pycurl working!  I think the error you are now observing was reported in issue #21.  There is a fix in the current version of `libbyfetch.py` found in the main branch of the repository.  Please download just that single source file from the main branch and see if that works for you.   Let me know if the error persists.

**Comment by OGQueenie** [comment]
Thank you! That seems to have fixed this issue but now I am receiving the same "Page says: An error was encountered while opening this audiobook." that the other users have reported when trying to download a book, Hopefully you can get that part sorted soon
